### Structure of a function

In [1]:
print("In the name of Allah")

In the name of Allah

In [5]:
def welcome_message() :
    print("Hello user")

In [6]:
welcome_message()

Hello user

In [8]:
def welcome_message(user) :
    print(f"Hello {user}")

In [11]:
welcome_message()

TypeError: welcome_message() missing 1 required positional argument: 'user'

In [12]:
welcome_message("Akib")

Hello Akib

In [15]:
def welcome_message(user = "None") :
    print(f"Hello {user}")

welcome_message()

Hello None

In [18]:
def adder(a, b) :
    sum = a + b
    return sum

In [20]:
m = adder(10, 30) * 5
print(m)

200

In [27]:
def adder(a, b) :
    """
    add two numers
    a -> int
    b -> int
    """
    sum = a + b
    return sum

In [28]:
m = adder(10, 30) * 5
print(m)

200

In [29]:
help(adder)

Help on function adder in module __main__:

adder(a, b)
    add two numers
    a -> int
    b -> int

In [30]:
help(print)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.

    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.

### Different type of argument

In [32]:
def adder(a, b, c) :
    print(f"{a}, {b}, {c}")

adder(10, 30, 20)

10, 30, 20

In [34]:
def adder(*args) :
    for i in args :
        print(i)

adder(10, 30, 20, 40)

10
30
20
40

In [35]:
def adder(a, b, c) :
    print(f"{a}, {b}, {c}")

adder(a = 10, c = 30, b = 20)

10, 20, 30

In [36]:
def adder(**kwargs) :
    print(kwargs)
adder(a = 10, b = 30, c = 40, n_estimator = 50)

{'a': 10, 'b': 30, 'c': 40, 'n_estimator': 50}

In [37]:
def adder(**kwargs) :
    for key,value in kwargs.items() :
        print(f"{key} : {value}")
        
adder(a = 10, b = 30, c = 40, n_estimator = 50)

a : 10
b : 30
c : 40
n_estimator : 50

### Return type

In [38]:
def welcome_message() :
    print("Hello user")

print(type(welcome_message()))

Hello user
<class 'NoneType'>

In [39]:
def adder(a, b) :
    sum = a + b
    return sum

print(type(adder(10, 20)))

<class 'int'>

In [41]:
def adder(a, b) :
    sum = a + b
    return sum

print(type(adder(10.5, 20)))

<class 'float'>

In [43]:
def welcome_message(user = "None") :
    return f"Hello {user}"

print(type(welcome_message()))

<class 'str'>

In [45]:
def adder(a, b) :
    return a, b

print(type(adder(10.5, 20)))

<class 'tuple'>

In [47]:
# unzip
x, y = adder(10.5, 20)
print(x)
print(y)

10.5
20

In [48]:
def adder(a, b) :
    return [a, b]

print(type(adder(10.5, 20)))

# unzip
x, y = adder(10.5, 20)
print(x)
print(y)

<class 'list'>
10.5
20

### iterator

In [50]:
s = {10, 20, 30, 40, 50}
print(s[1])

TypeError: 'set' object is not subscriptable

In [55]:
s = {10, 20, 30, 40, 50}
s_iter = iter(s)

print(next(s_iter))
print(next(s_iter))
print(next(s_iter))
print(next(s_iter))
print(next(s_iter))

50
20
40
10
30

In [56]:
for i in s:
    print(i)

50
20
40
10
30

### Generator

In [2]:
lst = [ x for x in range(500) ] # dataset

print(lst)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499]

In [11]:
def data_loader(chunk_size, lst) :
    for i in range(0, len(lst), chunk_size) :
        yield lst[i : i + chunk_size]

x = data_loader(5, lst)

print(type(x))
print(x)

<class 'generator'>
<generator object data_loader at 0x0000023110F0F010>

In [12]:
print(next(x))
print(next(x))

[0, 1, 2, 3, 4]
[5, 6, 7, 8, 9]

### Lambda, Map and Apply function

In [15]:
import pandas as pd


df = pd.DataFrame( {'temperature (F)': [32, 212, 98.6, 68]} )
df

   temperature (F)
0             32.0
1            212.0
2             98.6
3             68.0

In [16]:
df['temperature (C)'] = df['temperature (F)'].apply( lambda x : (x - 32) * 5/9 )
df

   temperature (F)  temperature (C)
0             32.0              0.0
1            212.0            100.0
2             98.6             37.0
3             68.0             20.0

In [21]:
import pandas as pd


df = pd.DataFrame({'A': [1, 2, 3, 4], 'B': [5, 6, 7, 8]})

df

df['A'] = df['A'].map(lambda x: x ** 0.5)

df

          A  B
0  1.000000  5
1  1.414214  6
2  1.732051  7
3  2.000000  8

In [22]:
import pandas as pd

df = pd.DataFrame({'A': [1, 2, 3, 4], 'B': [5, 6, 7, 8]})

df

df['A'] = df['A'].apply(lambda x: x ** 0.5)

df

          A  B
0  1.000000  5
1  1.414214  6
2  1.732051  7
3  2.000000  8

In [23]:
import pandas as pd

df = pd.DataFrame({'total_spent': [120, 600, 450, 800]})

# Creating a 'High Value' feature on the fly
df['is_high_value'] = df['total_spent'].apply(lambda x: 1 if x > 500 else 0)

df

   total_spent  is_high_value
0          120              0
1          600              1
2          450              0
3          800              1